name: "Baidu Tieba Auto Sign"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * *"
jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: "Start signing in"
        env:
          BDUSS: ${{ secrets.BDUSS }}
          HOST: ${{ secrets.HOST }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          AUTH: ${{ secrets.AUTH }}
        run: go run main.go
