name: "Baidu Tieba Auto Sign"

on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 4 * * *"

jobs:
    tieba_sign:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12.2"
            - run: python -m pip install --upgrade requests
            - name: "开始签到"
              env:
                  BDUSS: ${{ secrets.BDUSS }}
                  HOST: ${{ secrets.HOST }}
                  FROM: ${{ secrets.FROM }}
                  TO: ${{ secrets.TO }}
                  AUTH: ${{ secrets.AUTH }}
              run: python main.py
